# Generated by Django 4.2.3 on 2023-07-28 09:34

from django.db import models, migrations
import django


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(null=True, verbose_name='Фамилия'),
        ),
    ]
